# Generated by Django 5.2 on 2025-07-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('cor', models.CharField(default='#007bff', max_length=7)),
                ('prioridade_padrao', models.IntegerField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
